/* Paraphrased from the supplied manuscript, Appendix A (pages 21–22). */
window.GAME_DETAILS = {
 Pacman:{intro:'A symmetric maze contest built around collecting beans, avoiding monsters and disrupting an opponent. High-value beans reward route planning, while mines change which routes are safe.',decisions:['Choose routes through ordinary and high-value beans.','Balance collection against monster avoidance and collisions.','Place mines to constrain the opposing player.'],focus:'Collection, movement and disruption jointly determine the score.',page:21},
 SnakeGo:{intro:'A territory game in which snakes move, collect items and claim cells. Splitting and special actions create choices beyond simple collision avoidance.',decisions:['Keep movement safe without giving up valuable territory.','Use items and special actions to support expansion.','Balance local survival against territory at settlement.'],focus:'A safe move now can reduce the territory available later.',page:21},
 Rollman:{intro:'An asymmetric maze contest with two different roles. One side collects beans and uses temporary skills; the other controls ghosts that pursue and intercept it.',decisions:['Plan collection routes and time skills as the runner.','Coordinate ghosts to intercept rather than independently chase.','Account for different objectives and action spaces on each side.'],focus:'Runner and ghost policies solve different planning problems.',page:21},
 MoneCraft:{intro:'A resource-control game played on a symmetric map. Captured mines generate currency, while teleportation, observers and purchased protection affect control of the map.',decisions:['Capture and retain productive mines.','Trade movement and disruption against steady income.','Allocate currency to protection and map control.'],focus:'The referee settles the game using currency and mine ownership.',page:21},
 AntWar:{intro:'Tower defence combined with economic management. Players build towers, upgrade their bases and use super-weapons while the environment controls ant movement.',decisions:['Place and upgrade towers to cover incoming pressure.','Balance current defence against base development.','Time super-weapons around the evolving board state.'],focus:'Policies shape defence and spending rather than directly steering ants.',page:21},
 LostSpace:{intro:'A multiplayer survival-and-escape game on a layered map that contracts over time. Players gather supplies and keys, use tools and decide when to fight, evade or attempt an escape.',decisions:['Collect the supplies and keys needed for an escape.','Navigate the contracting map while avoiding unnecessary fights.','Choose when survival is worth more than immediate combat.'],focus:'Ranked outcomes reward both survival and well-timed escape attempts.',page:21},
 AquaWar:{intro:'A tactical game with hidden fish identities. Players choose a roster, make assertions about opponents’ identities and select attacks or type-specific skills.',decisions:['Choose a roster with complementary abilities.','Infer hidden identities from available information.','Time attacks and skills around uncertain opponent types.'],focus:'Roster design, inference and tactical timing all affect the result.',page:21},
 Generals:{intro:'A strategy game combining territorial expansion and army control with neutral assets, production, technology and tactical abilities.',decisions:['Expand and develop an economy that supports the army.','Allocate forces between neutral assets, defence and attack.','Coordinate technology and abilities with an offensive.'],focus:'Economic development and military movement must be planned together.',page:21},
 Dorado:{intro:'A resource and combat game in which players choose heroes, produce and command units, harvest neutral resources and invest in upgrades.',decisions:['Assign units to harvesting while maintaining combat strength.','Develop heroes without exhausting production income.','Coordinate movement and abilities to pressure opposing bases.'],focus:'The paper documents how mining assignments and hero investment improved GLM-5.3’s policy.',page:21},
 Miracle:{intro:'A hex-grid strategy game with heterogeneous units and an initial draft. Players select creatures and an artifact, then summon, move, attack and use abilities against the opposing miracle.',decisions:['Draft creatures and an artifact that work together.','Allocate limited resources between summons and tactical actions.','Coordinate unit interactions to destroy the opposing miracle.'],focus:'Unit composition and tactical coordination are central to the game.',page:21},
 LOTA:{intro:'A lane-based combat game centred on a player-controlled hero. Units advance along fixed lanes while the hero moves, attacks, develops skills, uses abilities and revives.',decisions:['Coordinate hero movement and abilities during fights.','Develop skills and manage revival.','Convert lane pressure into damage to defensive structures.'],focus:'Victory follows base destruction or the referee’s turn-limit settlement.',page:21},
 AntWar2:{intro:'Tower defence with ordered operation lists whose accepted prefix changes subsequent decisions. Players coordinate tower placement, economic development and weapon timing while respecting sequence-dependent legality.',decisions:['Choose a legal sequence, not just individually valid operations.','Use purchases and sales to support later operations in the round.','Coordinate defensive coverage, development and weapon timing.'],focus:'Each operation is checked against the state after the accepted prefix. Ant movement and combat are handled by the environment.',page:22}
};
