/* Reader-facing rules, summarized from the competition documents and Arena backends.
 * These are gameplay guides, not a replacement for the executable referee.
 * Source paths are relative to each game's package in AHL-Arena. Reviewed 2026-10-08.
 */
window.GAME_RULES = {
 Pacman: {
  intro: 'Two players race for points in the same maze while four computer-controlled monsters patrol it. Collect beans, use Magic Beans to turn danger into an advantage, and place mines to disrupt the other player. Neither player controls the monsters.',
  facts: [['Players','2'],['Map','20 × 20 maze'],['Starting score','100 each'],['Limit','600 rounds']],
  sections: [
   {title:'Map and objective',paragraphs:['Walls block movement; corridors contain ordinary beans and Magic Beans. Players and monsters have fixed spawn locations. Characters do not block one another: sharing a cell is allowed, although contact with a monster may cause damage. The objective is the higher score, not simply the number of beans collected.']},
   {title:'A round of play',steps:['Both programs receive the same pre-movement board, including players, monsters, remaining beans and active mines. Each chooses a direction, a movement length and an optional mine placement.','The referee computes monster movement and shortens player movement when walls obstruct the requested path. Normal movement is one cell; a powered-up player can move up to two cells in a straight line.','Movement, bean collection, monster encounters and mine crossings are resolved. Timers advance, beans regenerate and dead monsters return after their respawn delay.'],paragraphs:['Two-cell movement cannot turn a corner halfway through. Collision checks consider movement during the round, not only the final cells: a player and a monster swapping places can collide.']},
   {title:'Beans, power-ups and scoring',table:{headers:['Event','Effect'],rows:[['Ordinary bean','+1 point; returns after 40 rounds.'],['Magic Bean','+5 points, one mine, and a temporary speed / invulnerability state.'],['Powered-up movement','Up to 2 cells per round; the configured power-up timer is 10 rounds.'],['Kill a monster while powered up','+10 points; the monster respawns after 5 rounds.'],['Hit a monster without protection','−20 points.'],['Cross a mine without protection','−20 points, including mines you placed yourself.']]}},
   {title:'Mines and simultaneous events',paragraphs:['A mine can be placed on a legal non-wall cell; it is not restricted to the cell occupied by its owner. Monsters ignore mines. A powered-up player can clear a mine without the ordinary score penalty.','Both players can receive the same bean reward or mine penalty when they encounter that object in the same round. The board is not resolved as “the first program claims everything before the second program moves.”']},
   {title:'End of the game',paragraphs:['The game ends after 600 rounds, or early when a player has a negative score and the two scores are unequal. If both players have the same negative score, play continues. The higher final score wins; equal final scores remain tied.','The original document describes 0.1-second logical rounds. That describes the game timeline, not a one-minute wall-clock limit on an AI evaluation.']}
  ],
  sources:['2012 competition rulebook: Pacman 游戏规则 V1.0 (25 October 2012).','backend/resources.res; backend/logic/src/GameInfo.cc, Player.cc, Monster.cc and Constants.cc.']
 },
 MoneCraft: {
  intro:'Two players compete to control gold mines in a maze. Holding mines generates income, while movement, blinking, scouting and temporary protection determine who can retain them. The deployable objects are observers for vision—not explosive mines.',
  facts:[['Players','2'],['Map','31 × 31'],['Mine income','10 gold / round'],['Default limit','1,000 rounds']],
  sections:[
   {title:'Map and information',paragraphs:['The arena is a symmetric maze containing fixed gold-mine locations. Each player controls one mobile character. Observations distinguish visible terrain from unseen cells; observers extend information beyond the character’s immediate surroundings.','A mine stores an owner, a capture-progress value and a protection timer. Arriving at a mine is not the same as instantly owning it.']},
   {title:'Capturing and holding mines',paragraphs:['Standing on a mine shifts its control progress toward your side. Progress runs between the two ownership endpoints, −5 and +5; an enemy mine must first be neutralized before it becomes yours. Defending your own mine restores its control toward your endpoint.','Temporary protection prevents the ordinary hostile capture-progress change. Mine ownership is updated before the round’s movement, so a move onto a mine starts affecting capture on a subsequent update. Occupied mines generate gold for their owner.']},
   {title:'Available actions',table:{headers:['Action','Rule'],rows:[['Move / stay','Move one cell through legal terrain, or remain in place.'],['Blink','Jump to a legal destination within Euclidean distance 2.9 when cooldown permits.'],['Place observer','Leave a vision-providing observer at the pre-movement position; it lasts about 50 rounds and can be removed by an opponent occupying its cell.'],['Protect a mine','At an owned mine, buy 80 rounds of protection. The price is 100 × the number of mines you own.']]} ,paragraphs:['Blink cooldown grows with your holdings: the base is 5 rounds plus 3 per owned mine. Observer cost scales with the number of your existing observers, using a coefficient of 10 gold. Both purchases spend the same currency that matters at the end.']},
   {title:'Round resolution',steps:['Collect both players’ commands from the current observations.','Update mine capture and ownership; count owned mines and observers.','Resolve movement, blinks and purchases, then age or remove observers.','Pay mine income and advance the round.'],paragraphs:['A failed movement check leaves the character in place. Purchases are checked against funds and ownership; an action field is not a guarantee that the action will execute.']},
   {title:'Winning and trade-offs',paragraphs:['At the fight-mode limit of 1,000 rounds, compare gold first and owned mine count second. If both are equal, the game is a draw.','Protection can preserve future income but reduces final cash immediately. More mines increase income while also making blinking slower and protection more expensive, so rapid expansion has a mobility and defence cost.']}
  ],sources:['Competition rulebook: MoneCraft 游戏规则 V3.0.','backend/logic/src/logic.cc and include/sdk.h; backend/resources.res (fight mode).']
 },
 Dorado:{
  intro:'El Dorado combines hero development, resource collection and base attacks. Two opposing camps buy and command heroes, compete around neutral gold resources and decide how much wealth to commit to combat rather than further development.',
  facts:[['Players','2 competing camps'],['Hero classes','4'],['Economy','Gold + hero investment'],['Default limit','1,000 rounds']],
  sections:[
   {title:'Battlefield and forces',paragraphs:['Each competing camp has a military base. Neutral units and gold resources occupy the map between the camps. Terrain and height constrain paths, so geometric proximity alone does not imply that a destination is reachable.','The purchasable hero classes are Hammerguard, Master, Berserker and Scouter. They differ in combat attributes and abilities. Neutral creatures are separate from the player’s purchased heroes.']},
   {title:'Economy and development',paragraphs:['Gold supports buying heroes, purchasing levels and using base services such as recalling or buying back heroes. Mining requires units to reach and work the relevant resource locations; several heroes sent to the same task can leave other resources uncontested.','Levels improve a hero’s capabilities but concentrate investment in fewer bodies. A camp must preserve enough combat power to defend its base while committing units to income generation.']},
   {title:'Commands and abilities',table:{headers:['Command family','Purpose'],rows:[['Move','Give a destination; the movement system follows legal terrain and paths.'],['Attack','Select an opposing target and let range, attack cooldown and defensive attributes determine combat.'],['Mine / interact','Assign resource work through the relevant unit abilities.'],['Hero skills','Use class-specific abilities subject to their target, resource and cooldown requirements.'],['Base services','Buy heroes and levels, recall heroes or buy them back.']]}},
   {title:'Round resolution',paragraphs:['Programs receive map and player information and return commands identifying units and actions. The engine updates movement, attacks, skill effects, buffs and resource state between decisions. A command can fail when its unit, target, range or prerequisites are no longer valid.','Combat includes delayed effects such as projectiles and temporary buffs. A successful command is therefore not necessarily an immediate damage event. Keeping track of living units and current assignments matters more than assuming that an earlier order is still useful.']},
   {title:'Victory and time-limit scoring',paragraphs:['Destroying the opposing military base wins; destruction of both bases is a draw. If neither base has fallen when the round limit is reached, the referee compares each camp’s property value.','Property is current gold plus the recorded purchase / level-investment value of that camp’s hero units. It is not simply base HP, kill count or unspent gold. Equal property produces a draw.']}
  ],sources:['第 20 届智能体大赛 El Dorado: reference.pdf and tutorial.pdf.','backend/logic/src/ElDorado.cpp, PlayerInfo.cpp, MilitaryBase.cpp, Heroes.cpp and frame.cpp.']
 },
 LOTA:{
  intro:'LOTA is a hero-combat game with opposing teams, defensive structures and neutral units. Choose a hero, use movement and abilities to control fights, earn experience and convert pressure into destruction of the enemy’s defences.',
  facts:[['Players','2 competing camps'],['Mode','Competitive'],['Progression','Experience + skills'],['Default limit','1,000 rounds']],
  sections:[
   {title:'Heroes and battlefield',paragraphs:['Each player chooses a hero and commands it on a shared battlefield with allied and enemy units. Hero classes have different health, attack, defence, movement, range and skill sets. Towers and other defensive units constrain approaches; neutral encounters offer additional combat opportunities.','This guide describes competitive play. The legacy package also contains tutorial missions with separate objectives and stopping conditions; those are not the rules of the competitive ladder.']},
   {title:'Actions available to a player',table:{headers:['Action','Purpose'],rows:[['Move','Reposition the hero along a legal route.'],['Attack','Engage a target within the hero’s attack and targeting constraints.'],['Cast','Use an active skill with the required mana, cooldown and target.'],['Develop skills','Spend earned development opportunities to improve the hero.'],['Revive','Return to play through the game’s death and revival mechanics.']]}},
   {title:'Combat and progression',paragraphs:['Attacks and skills are resolved using unit attributes, range, cooldowns and current buffs. Some effects create projectiles or areas that persist across updates instead of dealing all damage at command submission.','Experience supports development and also contributes to time-limit settlement. Death interrupts activity and triggers the applicable revival rules, giving the surviving side time to control the map or damage structures.']},
   {title:'Round flow',steps:['Read the current map, hero state and visible unit information.','Submit commands for movement, combat, skills or development.','The engine advances units, flights, area effects and buffs, then resolves deaths and experience.','Check whether a camp has lost its decisive structures or the round limit has been reached.']},
   {title:'Victory and ties',paragraphs:['The competitive referee tracks two decisive defensive structures per camp. Losing both loses the game; if neither camp retains any, the result is a draw.','At the round limit, compare surviving decisive structures first, their total HP second, and accumulated experience on the camps’ other units third. If all three comparisons are equal, the game is a draw. Kills alone are not the settlement rule.']}
  ],sources:['backend/logic/src/LOTA.cpp: competitive mode 0 winnerJudge; Heroes.cpp, Skills.cpp, Game.cpp and frame.cpp.']
 },
 AntWar:{
  intro:'Build a defence that stops enemy ants while helping your own ants reach the opposing base. Players manage towers, base upgrades and super-weapons; the engine—not the player—chooses the ants’ routes.',
  facts:[['Players','2'],['Board','Hex grid, 19 × 19 extent'],['Initial gold','50'],['Limit','512 rounds']],
  sections:[
   {title:'Board and objective',paragraphs:['The two camps occupy mirrored positions on a hexagonal map. Towers can be built only on legal sites. Ants spawn from bases and navigate using the game’s pheromone system; reaching the enemy base reduces its health.','Ant movement is indirect. Tower coverage, surviving routes, base production and temporary effects change the pressure on each side, but there is no “move this ant to this cell” action.']},
   {title:'Economy and construction',paragraphs:['Each camp starts with 50 gold and receives a basic income of 1 per round, with additional income from combat. New towers become progressively more expensive as the camp’s tower count increases.','Basic towers can be upgraded along the legal upgrade tree into specialised attack types. Upgrading costs gold; downgrading or dismantling returns part of the investment. Base development separately improves production speed and ant strength.']},
   {title:'Operations',table:{headers:['Operation','Effect'],rows:[['Build / upgrade tower','Add coverage or change a tower’s damage, firing rate, range or special effect.'],['Downgrade / dismantle','Recover gold and reorganise the defence.'],['Upgrade production','Reduce the interval between newly generated ants.'],['Upgrade ants','Improve the generated ants’ health level.'],['Lightning storm','Use a damaging super-weapon in a selected area.'],['EMP, deflector, emergency evasion','Apply disruption or protection effects subject to cost, range and cooldown.']]}},
   {title:'A round of play',steps:['Player 0 submits its operations; player 1 receives the updated information and submits its operations.','The engine resolves tower attacks, ant movement and the resulting combat or base damage.','New ants, income, pheromone changes and temporary-effect timers are processed.','The referee checks base destruction and the round limit.'],paragraphs:['A player can submit multiple operations, but each still needs a valid target, sufficient gold and any required cooldown.']},
   {title:'Winning and time-limit settlement',paragraphs:['A camp loses when its base reaches zero HP. If both are zero at the same settlement, the backend selects player 0.','At the 512-round limit, the backend compares base HP, enemy ants killed, fewer super-weapon uses and lower accumulated AI time, in that order. A complete tie is awarded to player 0.']}
  ],sources:['games/antwar/rules.md; backend game.cpp, main.cpp, common.hpp and operation.h.']
 },
 AntWar2:{
  intro:'AntWar2 keeps the ant-routing and tower-defence structure while changing the economy and movement system. Each decision is an ordered list: an earlier purchase, sale or upgrade can change whether a later operation is legal.',
  facts:[['Players','2'],['Base health','50 each'],['Initial gold','50'],['Limit','512 rounds']],
  sections:[
   {title:'Board and units',paragraphs:['The game uses a 19 × 19 offset-hex grid, with bases at (2, 9) and (16, 9). Ants are generated and moved by the environment. Players shape their routes and survival through construction, development and area effects.','The public state includes bases, ants, coins, towers and weapon cooldowns. Tower updates are a delta stream: creation, changes and deletions must be applied to the remembered board. The bundled SDK maintains this state for the player.']},
   {title:'Ordered decisions',paragraphs:['Submit a list of operations, or an empty list to hold. Each operation is checked against the board and resources after the operations already accepted in that list. An apparently valid action on the initial board can become invalid after an earlier action.','Checks include board bounds, buildable ownership, occupation, tower ownership, the upgrade tree, duplicate use, EMP restrictions, gold, cooldowns and level limits. Selling to fund a later purchase and buying before upgrading are different sequences.']},
   {title:'Costs and development',table:{headers:['Action / resource','Value'],rows:[['Basic income','3 gold every 2 rounds.'],['Next tower, with n existing towers','15 × 3^floor(n/2), doubled when n is odd.'],['Tower upgrades','60 / 200 gold for the two upgrade tiers.'],['Production-speed upgrade','200 gold.'],['Generated-ant upgrade','250 gold.'],['Lightning / EMP','90 / 135 gold.'],['Deflector / emergency evasion','60 / 60 gold.']]}},
   {title:'Environment resolution',paragraphs:['After operations, the environment resolves ant routing, tower combat, generation, active effects and base damage. Routing uses the backend’s pheromone and movement-planning machinery; a player cannot bypass it with direct ant commands.','Tower placement therefore affects both local coverage and the value of future routes. Temporary weapons have their own active effects and cooldowns, so spending all available gold is not necessarily a useful operation sequence.']},
   {title:'Victory',paragraphs:['Reducing the opposing base to zero HP wins; simultaneous zero HP is resolved in favour of player 0.','At 512 rounds, compare base health, enemy ants killed, fewer super-weapon uses and lower accumulated AI time. A complete tie goes to player 0. These are backend tie-breaks, not Elo adjustments.']}
  ],sources:['games/antwar2/rules.md and decision_space.yaml, checked against the bundled C++ backend.']
 },
 AquaWar:{
  intro:'A hidden-identity tactical battle between teams of fish. Each player selects four fish, infers the opposing lineup from attacks and passive effects, and alternates identity assertions with combat actions across a best-of-three match.',
  facts:[['Players','2'],['Lineup','4 of 12 fish types'],['Base attributes','400 HP / 100 ATK'],['Match','Best of 3']],
  sections:[
   {title:'Lineups and hidden information',paragraphs:['At selection, choose four distinct fish types from the currently available roster. If choosing the imitator, also name the fish type it will mimic. Your own identities are known; unrevealed enemy identities are hidden even though enemy health and public combat events are visible.','The twelve types include sprayfish, flamefish, eel, sunfish, barracuda, mobula, turtle, octopus, white shark, hammerhead shark, clownfish and imitator. They differ in active skills and passive reactions, not just attack values.']},
   {title:'Match and turn order',steps:['Prepare the subgame and select a four-fish lineup for each side. Player 0 moves first in the first subgame; the previous loser moves first in subsequent subgames.','The active player can assert the identity of an enemy fish or skip the assertion. A correct assertion reveals the identity and triggers its associated effect.','Choose one living friendly fish to make a normal attack or use its active skill with legal targets.','Alternate sides until the subgame ends, acknowledge the result and continue the match if required.']},
   {title:'Attacks, skills and passives',table:{headers:['Mechanic','What it changes'],rows:[['Normal attack','One living fish attacks a legal enemy target.'],['Active skill','May use enemy targets, friendly targets, multiple targets or a fish-specific targeting rule.'],['Passive reactions','Can redirect damage, counterattack, heal, evade or trigger on death.'],['Shield / recovery / deflection buffs','Modify later damage events and may be consumed when triggered.'],['Imitation','Gives the imitator the chosen type’s abilities for that subgame.']]} ,paragraphs:['Damage can trigger further effects before the final state is settled. Inferring a hidden identity therefore requires reading the event sequence, not only subtracting HP from the previous observation.']},
   {title:'Legal actions and observation',paragraphs:['Pick exactly four distinct eligible IDs. Combat actions identify a friendly fish and the target positions; skill target counts and restrictions depend on that fish. Dead fish cannot be used as living attackers, and target lists cannot arbitrarily include duplicate positions.','Programs receive their own fish information, the enemy’s public information, summaries of the opponent’s last assertion or action, and subgame results. Hidden fish IDs should not be assumed known until disclosed.']},
   {title:'Winning',paragraphs:['Eliminating the enemy lineup wins the subgame. The match is settled after a side wins two subgames or the three-subgame sequence is exhausted.','A subgame also has a backend state-advance limit of 128. When it is exceeded, compare surviving fish count, total remaining HP, highest individual HP and finally the second-moving side. This is a state-machine limit, not 128 complete pairs of combat turns.']}
  ],sources:['games/aquawar/rules.md; backend fish, lineup, game-state and aqua_sdk implementations.']
 },
 Generals:{
  intro:'Expand territory, build an economy and manoeuvre armies to capture the opposing main general. Generals combines grid-based military movement with oil income, general upgrades, technologies, tactical skills and super-weapons.',
  facts:[['Players','2'],['Map','15 × 15'],['Initial gold','40 each'],['Limit','Settlement after round 500']],
  sections:[
   {title:'Terrain and objectives',paragraphs:['Each cell has terrain, an owner, an army count and possibly a general or oil well. Plains are traversable. Mountains require the relevant technology; unprotected swamp holdings lose soldiers during round updates.','Each player starts with a main general. Neutral secondary generals and oil wells offer expansion targets: generals produce soldiers, while owned oil wells produce gold. Capturing the enemy main general is the immediate victory objective.']},
   {title:'Movement and combat',paragraphs:['Army movement transfers soldiers from an owned cell to an adjacent legal cell, leaving at least one soldier behind. Movement consumes the player’s remaining army-move allowance, initially two steps per round. Friendly destinations reinforce; hostile destinations resolve combat.','Combat compares attacking strength with defending strength after modifiers. The stronger side retains the surviving force; an exact strength tie clears the army and neutralizes the cell. Generals can move separately, subject to their mobility and path restrictions.']},
   {title:'Economy, technology and actions',table:{headers:['Action family','Choices'],rows:[['Move armies / generals','Redistribute troops, capture cells and relocate generals.'],['Upgrade a general','Improve production, defence or mobility where that general type allows it.'],['Tactical skills','Surprise attack, rout, command, defence and weakening; each has cost and cooldown constraints.'],['Technology','Increase army movement, enable mountain travel, gain swamp immunity or unlock super-weapons.'],['Super-weapons','Nuclear attack, attack enhancement, transmission and time stop.'],['Recruitment','Spend gold to create the allowed secondary-general presence.']]}},
   {title:'Round structure',steps:['Player 0 submits a sequence of commands; commands take effect in order.','Player 1 acts on the resulting position and submits its sequence.','After player 1 finishes, produce soldiers and oil income, apply swamp loss and ongoing effects, and update cooldowns.','Reset movement allowances and check the next round.'],paragraphs:['Every ten rounds, owned cells receive an additional soldier. Within a command batch, an earlier move or expenditure can change the legality and outcome of later commands.']},
   {title:'Victory and visibility',paragraphs:['Losing the main general loses the game immediately. After round 500, if both main generals survive, compare total soldiers, owned cells and gold, in that order; a complete tie goes to player 0.','The competitive interface provides the board, generals, coins, technologies and weapon state rather than a fog-of-war exploration problem. Strategic uncertainty comes primarily from the opponent’s future choices.']}
  ],sources:['games/generals/rules.md; backend main.py and logic/{gamestate,movement,computation,upgrade,general_skills,super_weapons}.py.']
 },
 LostSpace:{
  intro:'Four players explore a shrinking, multi-level space station. Gather keys and supplies, fight or evade rivals, and reach the escape capsule before the station becomes uninhabitable. The result is a four-player ranking, not just a binary duel.',
  facts:[['Players','4'],['Map','7 × 7 × 3'],['Maximum HP','200'],['Round cap','100']],
  sections:[
   {title:'Map and exploration',paragraphs:['Players begin near the four corners of a three-layer map. Connections, doors and elevators determine legal movement between locations. The escape capsule is at (3, 3, 0); key machines, boxes and supply locations provide the resources needed to survive and escape.','Information is local: visibility and witness messages report only the actions and state available to the player. A remembered enemy location may no longer be current. Supply locations refresh every eight rounds.']},
   {title:'Turn and action budget',paragraphs:['Players act in order within each global round. At the start of an active turn, the player’s action-point budget is reset to one, and delayed events such as respawn, key acquisition and escape are processed.','A turn can contain several request / response exchanges. Submit movement, combat, interactions, traps, tools or detection as permitted, then finish the turn. Different operations have different prerequisites and action-point costs; a successful free operation does not automatically end the turn.']},
   {title:'Actions and equipment',table:{headers:['Action / item','Use'],rows:[['Move','Travel to a connected, reachable location.'],['Attack','Strike a valid rival at a specified location; base damage is 70.'],['Interact','Use a key machine, open a box, take supplies or enter the escape process.'],['Land mine / sticky trap','Damage or hinder players using the trapped location; land-mine damage is 120.'],['Medical kit / transport','Recover 100 HP up to the health cap, or use the permitted teleport effect.'],['Detect','Inspect a location for traps, subject to the detection cooldown.']]}},
   {title:'Shrinking map and escape',paragraphs:['The map contracts at scheduled rounds 40, 50, 60, 70 and 80. Paths and safe locations that worked earlier may become unavailable. The late phase disables ordinary revival, making death more costly.','Escape is a staged interaction involving the required keys and a waiting period, not an instantaneous reward for touching the capsule. While waiting to escape, the available actions are restricted.']},
   {title:'Ranking',paragraphs:['Successful escapees are ranked first in escape order. Remaining unsettled players are ordered by their accumulated score with the backend’s later-player tie-break; eliminated players follow the game’s elimination ordering.','The final places receive 4, 3, 2 and 1 points. A program should therefore distinguish winning an encounter, surviving until settlement and securing an early escape: they are not the same objective.']}
  ],sources:['games/lostspace/rules.md; backend/src/GameController.py, player.py, config.py and mapconf2.map.']
 },
 Miracle:{
  intro:'Draft a small army and an artifact, then summon creatures onto a hexagonal battlefield. Manage mana, deployment, movement and unit interactions to damage the opposing miracle while defending your own.',
  facts:[['Players','2'],['Draft','3 creatures + 1 artifact'],['Board','Hexagonal'],['Limit','100 player-turn advances']],
  sections:[
   {title:'Draft and battlefield',paragraphs:['Each side chooses three distinct creature types and one artifact before normal play. Creature types include swordsmen, archers, black bats, priests and the two dragons. Artifacts provide powerful targeted effects, such as holy light, inferno or shielding.','The mirrored map contains the two miracles, summoning positions, barracks and obstacles. Coordinates use the cube convention x + y + z = 0; distance, path length and legal landing cells are determined on this hex grid.']},
   {title:'Mana, summoning and cooldowns',paragraphs:['Mana limits summons and artifact use. A summon must use a drafted creature, a legal available level, sufficient capacity and mana, and a free friendly summoning location. Creature cards and artifacts have their own cooldown or readiness state.','Turn-start refresh updates resources, cooldowns and unit action availability. Newly summoned creatures do not receive ordinary movement and attack availability immediately.']},
   {title:'Actions within a turn',table:{headers:['Action','Requirements'],rows:[['Summon','Drafted card, available capacity, mana and a legal summoning cell.'],['Move','Owned creature, reachable unoccupied destination and sufficient movement range.'],['Attack','Living hostile target in attack range; flying targets require the appropriate capability.'],['Use artifact','Ready artifact, sufficient mana and a legal unit or position target.'],['End turn / surrender','Finish the action sequence or concede the game.']]} ,paragraphs:['One turn may contain many operations. Each is checked and settled before the program receives an updated position for its next choice. Non-agile creatures cannot freely combine movement and attack; agility permits that combination.']},
   {title:'Combat interactions',paragraphs:['An attack can trigger damage reactions, retaliation and death checks. Holy shield cancels an incoming damage event before breaking. Priests provide supporting effects, while dragon attacks can affect more than a single unit.','Ground and flying units obey different occupancy and targeting constraints. A unit that can reach a hex is not necessarily able to attack every enemy on it.']},
   {title:'Victory and score',paragraphs:['Play ends when a miracle is destroyed or the backend reaches 100 player-turn advances. The score heavily rewards damage to the enemy miracle: each HP lost contributes 1,000 points; enemy creature deaths also add their level to the score.','The higher terminal score wins. If scores are equal, the backend adds a point to the second player, so the tie is resolved in favour of that player. The round counter advances when the active player changes, not only after both players have acted.']}
  ],sources:['games/miracle/rules.md; backend/main.py, PlayerLegality/operations.py, StateSystem/Player.py and logic.md.']
 },
 Rollman:{
  intro:'An asymmetric chase game: one player controls the runner, while the other simultaneously commands three ghosts. The runner collects beans and power-ups; the ghosts coordinate pursuit, break shields and deny collection.',
  facts:[['Players','2 asymmetric roles'],['Ghosts','3, jointly controlled'],['Levels','3'],['Level caps','500 / 400 / 300 rounds']],
  sections:[
   {title:'Roles and levels',paragraphs:['The runner and ghosts have different action spaces and scoring rules. A runner policy chooses one direction per update; the ghost policy chooses a separate direction for each of its three ghosts. Both roles can stay still or move in a cardinal direction.','The match progresses through three generated mazes with decreasing dimensions. New levels reset their board layout and local state; the program must process the new initialization rather than continue using the previous maze.']},
   {title:'Beans and powers',table:{headers:['Pickup','Effect'],rows:[['Regular / bonus bean','1 / 2 runner points before score modifiers.'],['Double-score bean','Doubles bean rewards temporarily.'],['Speed bean','Allows two-step movement temporarily.'],['Magnet bean','Collects beans in the surrounding 3 × 3 neighbourhood.'],['Shield bean','Adds protection against a capture; shields can accumulate.'],['Freeze bean','Temporarily forces ghosts to stay still.']]} ,paragraphs:['Double score, speed and magnet use eight-round durations; freezing uses two. Shields are consumed by capture interactions rather than being treated simply as a movement bonus. Portals become available under the level’s collection conditions.']},
   {title:'Movement and capture',paragraphs:['Both role commands are gathered before the environment advances. Walls limit movement; power-ups modify the resulting paths. Capture uses the paths travelled during the step, not only whether final coordinates match.','A shield can be broken without the same consequence as an unshielded capture. After captures, respawn and protection mechanics change the next pursuit opportunity, so the ghosts benefit from coordinating their approaches.']},
   {title:'How each side scores',table:{headers:['Event','Score change'],rows:[['Runner eats regular / bonus bean','+1 / +2, modified by double score.'],['Runner clears all beans','+50.'],['Runner reaches the collection milestone','+50 at the 100-bean threshold.'],['Unshielded runner is caught','Runner −60; capturing ghost reward +50.'],['Ghost breaks a shield','Ghost side +10.'],['Ghosts prevent full collection','Additional prevention reward under the level settlement.']]}},
   {title:'Match result',paragraphs:['Levels end through their completion or time-limit conditions, and the match settles the scores accumulated by the two roles. The referee reports the runner score and the ghost-side score mapped back to the players that held those roles.','Because the roles differ, a candidate’s strength cannot be inferred from runner-only results. Arena evaluation uses role-aware matchups; its tie mapping favours the first player when the reported scores are exactly equal.']}
  ],sources:['games/rollman/rules.md; backend/core/gamedata.py, GymEnvironment.py, pacman.py, ghost.py and main.py.']
 },
 SnakeGo:{
  intro:'Turn snake movement into territory. Grow and split your snakes, use self-biting loops to solidify enclosed cells, and destroy walls with collected firing items. Surviving bodies and permanent territory both count at settlement.',
  facts:[['Players','2'],['Default map','16 × 16'],['Snake cap','4 per side'],['Default limit','512 rounds']],
  sections:[
   {title:'Starting state and turn order',paragraphs:['Each side begins with one snake. The initial snakes automatically grow during the first eight rounds; later growth comes from stored length gained through items.','Players act in order. During one player’s turn the backend requests operations for the snakes that remain eligible to act, potentially making several request / response exchanges before control passes to the opponent. Items appear and expire according to the seeded schedule.']},
   {title:'Movement and territory',paragraphs:['A move advances the head one cell. If growth is available, the tail stays; otherwise the tail contracts. Moving out of bounds, into a wall or into another snake’s body kills the moving snake. Immediate reversal into the neck is illegal in the applicable length / growth states.','Biting your own body has a different purpose: the loop and enclosed region solidify into walls owned by your side, and that snake disappears. Enemy snakes enclosed by the solidification can also be killed. Territory gain therefore trades a mobile snake for permanent coverage.']},
   {title:'Operations and items',table:{headers:['Action / item','Rule'],rows:[['Move','Choose one of four cardinal directions.'],['Fire','With a firing item and a body long enough to define heading, clear walls along the head’s forward row or column.'],['Split','Divide the current snake around its midpoint; the new tail snake is reversed. Length must exceed one and the side must have fewer than four snakes.'],['Length item','Adds stored growth, preserving the tail during later moves.'],['Firing item','Enables the wall-clearing action while available.']]}},
   {title:'Timing and legality',paragraphs:['Items are not permanent: uncollected items expire after their configured lifetime, and carried effects follow their own retention values. Newly split snakes and the current action order must be tracked through the updated state.','Firing without the required item, exceeding the snake cap, reversing illegally or submitting an invalid operation can cause a forfeit. A geometrically safe direction is not always a legal action for the current snake.']},
   {title:'Scoring and end conditions',paragraphs:['Each cell occupied by your snakes contributes two points; each owned wall cell also contributes two. The side that first collects an item receives an additional one-point bonus.','The game ends when both sides have no snakes left or the configured round limit is exceeded. Higher score wins; exact equality goes to player 0. Eliminating an enemy snake matters through territory and survival, rather than a separate kill score.']}
  ],sources:['games/snakego/rules.md; backend logic/constants.py, spawn.py, operate.py, result.py and infrastructure.py.']
 }
};
